### PR TITLE
Use appropriate bootstrap classes on clipform buttons

### PR DESCRIPTION
**Pull request by nikolas**
See attached screenshots for before and after.

2015-08-05-140806_98x51_scrot

2015-08-05-140810_98x51_scrot

### CODE REVIEW

**Comment by sdreher** [comment]
Cool. Can I also trouble you to fix the layout/spacing for these buttons while you are in there?

**Comment by nikolas** [comment]
Yeah, I'll include something to fix that in this pull request if it makes sense (like if it's not a mediathread CSS-specific thing).

**Comment by nikolas** [comment]
Here's what the updated clipform looks like:

2015-08-05-165244_282x141_scrot

This does require a few changes to mediathread:
```diff
diff --git a/media/css/mediathread.css b/media/css/mediathread.css
index 5de6eaa..cd4ce52 100644
--- a/media/css/mediathread.css
+++ b/media/css/mediathread.css
@@ -3583,10 +3583,6 @@ div.asset-view-container div.asset-view-tabs .ui-tabs-panel {
     -webkit-border-radius: 0;
 }
 
-div.asset-view-container div.asset-view-tabs .btn-primary {
-    margin: 3px 0 0 3px;
-}
-
 ul#asset-details-annotations-list h3.ui-accordion-header-active {
     border-bottom: 0;
     outline: 0;
@@ -4312,7 +4308,7 @@ div.ui-dialog div.asset-view-details h2 {
 }
 
 .switcher *,
-.form-control {
+.panel-container.collection .form-control {
     -webkit-box-sizing: border-box !important;
     -moz-box-sizing: border-box !important;
     box-sizing: border-box !important;
```

I can definitely see why it would be simpler if SherdJS was part of Mediathread.

I could also, instead stick with the table layout, but that would also require changes to mediathread's CSS.

The spacing between the clipform and the `Title:` label will need to be fixed in Mediathread.

**Comment by nikolas** [comment]
Because these big dom changes in the clipform here aren't that necessary for this release, I think I should just clean this up in a different way in a PR to mediathread. For now I'm going to spend some time looking for bugs related to the mustache upgrade, though.

**Pull request closed without merging**
